import { 
  Campaign, 
  CampaignStatus, 
  Task 
} from "../../../common/types/database/entity.types";
import { 
  AgentInvokeOptions,
  TaskExecutionResult,
  FinalMarketingReport,
  MarketingTaskMetadata
} from "../../../common/types/agent/agent.types";

// ==================== Input Types ====================

/**
 * Input parameters for creating and launching a campaign
 */
export interface CreateCampaignInput {
  userId: string;
  name: string;
  userPrompt: string;
  agentInvokeOptions: AgentInvokeOptions,
  description?: string;
  priority?: number;
  delay?: number;
}

// ==================== Output Types ====================

/**
 *  Campaign response type containing tasks, which are only included upon completion
 */
export interface CampaignWithTasks extends Campaign {
  tasks: Task[];
}

/**
 * Campaign execution progress
 */
export interface CampaignProgress {
  campaignId: string;
  status: CampaignStatus;
  message: string;
  taskStats?: {
    total: number;
    completed: number;
    failed: number;
  };
}

/**
 * Agent execution results
 * Contains the full marketing report and individual task execution results
 */
export interface AgentExecutionResult {
  success: boolean;
  /** The final marketing report generated by the agent */
  report: FinalMarketingReport;
  /** Individual task execution results from the agent */
  taskResults: TaskExecutionResult[];
  /** Error message if the overall execution failed */
  error?: string;
}

/**
 * Data required to create a Task entity from agent execution result
 * Maps TaskExecutionResult to database Task input
 */
export interface TaskCreateFromAgentData {
  campaignId: string;
  taskMeta: MarketingTaskMetadata;
  executionResult: TaskExecutionResult;
}

/**
 * List campaign's options 
 */
export interface ListUserCampaignsOptions {
  skip?: number;
  take?: number;
  status?: CampaignStatus;
  statusIn?: CampaignStatus[];
  orderBy?: { 
    field: "createdAt" | "updatedAt" | "name"; 
    direction: "asc" | "desc" 
  };
}
